In [1]:
import pandas as pd
import datetime as dt

In [2]:
ls -p . | grep /*csv

'grep' is not recognized as an internal or external command,
operable program or batch file.

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
def column_range(df,column):
    print(f'maximum is {max(df[column])} and minimum is {min(df[column])}')

In [5]:
def datetime_conversion(df,column):
    df[column] =  pd.to_datetime(df[column], format='%d/%m/%y')

In [6]:
coordinates_df=pd.read_csv('country-coordinates-world.csv')
coordinates_df

      latitude   longitude                                       Country
0    33.939110   67.709953                                   Afghanistan
1    41.153332   20.168331                                       Albania
2    28.033886    1.659626                                       Algeria
3   -14.270972 -170.132217                                American Samoa
4    42.546245    1.601554                                       Andorra
5   -11.202692   17.873887                                        Angola
6    18.220554  -63.068615                                      Anguilla
7   -75.250973   -0.071389                                    Antarctica
8    17.060816  -61.796428                           Antigua and Barbuda
9   -38.416097  -63.616672                                     Argentina
10   40.069099   45.038189                                       Armenia
11   12.521110  -69.968338                                         Aruba
12  -25.274398  133.775136                                     Australia
13   47.516231   14.550072                                       Austria
14   40.143105   47.576927                                    Azerbaijan
15   25.034280  -77.396280                                       Bahamas
16   25.930414   50.637772                                       Bahrain
17   23.684994   90.356331                                    Bangladesh
18   13.193887  -59.543198                                      Barbados
19   53.709807   27.953389                                       Belarus
20   50.503887    4.469936                                       Belgium
21   17.189877  -88.497650                                        Belize
22    9.307690    2.315834                                         Benin
23   32.321384  -64.757370                                       Bermuda
24   27.514162   90.433601                                        Bhutan
25  -16.290154  -63.588653                                       Bolivia
26   43.915886   17.679076                        Bosnia and Herzegovina
27  -22.328474   24.684866                                      Botswana
28  -54.423199    3.413194                                 Bouvet Island
29  -14.235004  -51.925280                                        Brazil
30   -6.343194   71.876519                British Indian Ocean Territory
31   18.420695  -64.639968                        British Virgin Islands
32    4.535277  114.727669                                        Brunei
33   42.733883   25.485830                                      Bulgaria
34   12.238333   -1.561593                                  Burkina Faso
35   -3.373056   29.918886                                       Burundi
36   12.565679  104.990963                                      Cambodia
37    7.369722   12.354722                                      Cameroon
38   56.130366 -106.346771                                        Canada
39   16.002082  -24.013197                                    Cape Verde
40   19.513469  -80.566956                                Cayman Islands
41    6.611111   20.939444                      Central African Republic
42   15.454166   18.732207                                          Chad
43  -35.675147  -71.542969                                         Chile
44   35.861660  104.195397                                         China
45  -10.447525  105.690449                              Christmas Island
46  -12.164165   96.870956                       Cocos [Keeling] Islands
47    4.570868  -74.297333                                      Colombia
48  -11.875001   43.872219                                       Comoros
49   -4.038333   21.758664                                   Congo [DRC]
50   -0.228021   15.827659                              Congo [Republic]
51  -21.236736 -159.777671                                  Cook Islands
52    9.748917  -83.753428                                    Costa Rica
53   45.100000   15.200000                                       Croatia
54   21.521757  -77.781167                                          Cuba
55   35.126413   33.429859                                        Cyprus
56   49.817492   15.472962                                Czech Republic
57    7.539989   -5.547080                                 Côte d'Ivoire
58   56.263920    9.501785                                       Denmark
59   11.825138   42.590275                                      Djibouti
60   15.414999  -61.370976                                      Dominica
61   18.735693  -70.162651                            Dominican Republic
62   -1.831239  -78.183406                                       Ecuador
63   26.820553   30.802498                                         Egypt
64   13.794185  -88.896530                                   El Salvador
65    1.650801   10.267895                             Equatorial Guinea
66   15.179384   39.782334                                       Eritrea
67   58.595272   25.013607                                       Estonia
68    9.145000   40.489673                                      Ethiopia
69  -51.796253  -59.523613             Falkland Islands [Islas Malvinas]
70   61.892635   -6.911806                                 Faroe Islands
71  -16.578193  179.414413                                          Fiji
72   61.924110   25.748151                                       Finland
73   46.227638    2.213749                                        France
74    3.933889  -53.125782                                 French Guiana
75  -17.679742 -149.406843                              French Polynesia
76  -49.280366   69.348557                   French Southern Territories
77   -0.803689   11.609444                                         Gabon
78   13.443182  -15.310139                                        Gambia
79   31.354676   34.308825                                    Gaza Strip
80   42.315407   43.356892                                       Georgia
81   51.165691   10.451526                                       Germany
82    7.946527   -1.023194                                         Ghana
83   36.137741   -5.345374                                     Gibraltar
84   39.074208   21.824312                                        Greece
85   71.706936  -42.604303                                     Greenland
86   12.262776  -61.604171                                       Grenada
87   16.995971  -62.067641                                    Guadeloupe
88   13.444304  144.793731                                          Guam
89   15.783471  -90.230759                                     Guatemala
90   49.465691   -2.585278                                      Guernsey
91    9.945587   -9.696645                                        Guinea
92   11.803749  -15.180413                                 Guinea-Bissau
93    4.860416  -58.930180                                        Guyana
94   18.971187  -72.285215                                         Haiti
95  -53.081810   73.504158             Heard Island and McDonald Islands
96   15.199999  -86.241905                                      Honduras
97   22.396428  114.109497                                     Hong Kong
98   47.162494   19.503304                                       Hungary
99   64.963051  -19.020835                                       Iceland
100  20.593684   78.962880                                         India
101  -0.789275  113.921327                                     Indonesia
102  32.427908   53.688046                                          Iran
103  33.223191   43.679291                                          Iraq
104  53.412910   -8.243890                                       Ireland
105  54.236107   -4.548056                                   Isle of Man
106  31.046051   34.851612                                        Israel
107  41.871940   12.567380                                         Italy
108  18.109581  -77.297508                                       Jamaica
109  36.204824  138.252924                                         Japan
110  49.214439   -2.131250                                        Jersey
111  30.585164   36.238414                                        Jordan
112  48.019573   66.923684                                    Kazakhstan
113  -0.023559   37.906193                                         Kenya
114  -3.370417 -168.734039                                      Kiribati
115  42.602636   20.902977                                        Kosovo
116  29.311660   47.481766                                        Kuwait
117  41.204380   74.766098                                    Kyrgyzstan
118  19.856270  102.495496                                          Laos
119  56.879635   24.603189                                        Latvia
120  33.854721   35.862285                                       Lebanon
121 -29.609988   28.233608                                       Lesotho
122   6.428055   -9.429499                                       Liberia
123  26.335100   17.228331                                         Libya
124  47.166000    9.555373                                 Liechtenstein
125  55.169438   23.881275                                     Lithuania
126  49.815273    6.129583                                    Luxembourg
127  22.198745  113.543873                                         Macau
128  41.608635   21.745275                             Macedonia [FYROM]
129 -18.766947   46.869107                                    Madagascar
130 -13.254308   34.301525                                        Malawi
131   4.210484  101.975766                                      Malaysia
132   3.202778   73.220680                                      Maldives
133  17.570692   -3.996166                                          Mali
134  35.937496   14.375416                                         Malta
135   7.131474  171.184478                              Marshall Islands
136  14.641528  -61.024174                                    Martinique
137  21.007890  -10.940835                                    Mauritania
138 -20.348404   57.552152                                     Mauritius
139 -12.827500   45.166244                                       Mayotte
140  23.634501 -102.552784                                        Mexico
141   7.425554  150.550812                                    Micronesia
142  47.411631   28.369885                                       Moldova
143  43.750298    7.412841                                        Monaco
144  46.862496  103.846656                                      Mongolia
145  42.708678   19.374390                                    Montenegro
146  16.742498  -62.187366                                    Montserrat
147  31.791702   -7.092620                                       Morocco
148 -18.665695   35.529562                                    Mozambique
149  21.913965   95.956223                               Myanmar [Burma]
150 -22.957640   18.490410                                       Namibia
151  -0.522778  166.931503                                         Nauru
152  28.394857   84.124008                                         Nepal
153  52.132633    5.291266                                   Netherlands
154  12.226079  -69.060087                          Netherlands Antilles
155 -20.904305  165.618042                                 New Caledonia
156 -40.900557  174.885971                                   New Zealand
157  12.865416  -85.207229                                     Nicaragua
158  17.607789    8.081666                                         Niger
159   9.081999    8.675277                                       Nigeria
160 -19.054445 -169.867233                                          Niue
161 -29.040835  167.954712                                Norfolk Island
162  40.339852  127.510093                                   North Korea
163  17.330830  145.384690                      Northern Mariana Islands
164  60.472024    8.468946                                        Norway
165  21.512583   55.923255                                          Oman
166  30.375321   69.345116                                      Pakistan
167   7.514980  134.582520                                         Palau
168  31.952162   35.233154                       Palestinian Territories
169   8.537981  -80.782127                                        Panama
170  -6.314993  143.955550                              Papua New Guinea
171 -23.442503  -58.443832                                      Paraguay
172  -9.189967  -75.015152                                          Peru
173  12.879721  121.774017                                   Philippines
174 -24.703615 -127.439308                              Pitcairn Islands
175  51.919438   19.145136                                        Poland
176  39.399872   -8.224454                                      Portugal
177  18.220833  -66.590149                                   Puerto Rico
178  25.354826   51.183884                                         Qatar
179  45.943161   24.966760                                       Romania
180  61.524010  105.318756                                        Russia
181  -1.940278   29.873888                                        Rwanda
182 -21.115141   55.536384                                       Réunion
183 -24.143474  -10.030696                                  Saint Helena
184  17.357822  -62.782998                         Saint Kitts and Nevis
185  13.909444  -60.978893                                   Saint Lucia
186  46.941936  -56.271110                     Saint Pierre and Miquelon
187  12.984305  -61.287228              Saint Vincent and the Grenadines
188 -13.759029 -172.104629                                         Samoa
189  43.942360   12.457777                                    San Marino
190  23.885942   45.079162                                  Saudi Arabia
191  14.497401  -14.452362                                       Senegal
192  44.016521   21.005859                                        Serbia
193  -4.679574   55.491977                                    Seychelles
194   8.460555  -11.779889                                  Sierra Leone
195   1.352083  103.819836                                     Singapore
196  48.669026   19.699024                                      Slovakia
197  46.151241   14.995463                                      Slovenia
198  -9.645710  160.156194                               Solomon Islands
199   5.152149   46.199616                                       Somalia
200 -30.559482   22.937506                                  South Africa
201 -54.429579  -36.587909  South Georgia and the South Sandwich Islands
202  35.907757  127.766922                                   South Korea
203  40.463667   -3.749220                                         Spain
204   7.873054   80.771797                                     Sri Lanka
205  12.862807   30.217636                                         Sudan
206   3.919305  -56.027783                                      Suriname
207  77.553604   23.670272                        Svalbard and Jan Mayen
208 -26.522503   31.465866                                     Swaziland
209  60.128161   18.643501                                        Sweden
210  46.818188    8.227512                                   Switzerland
211  34.802075   38.996815                                         Syria
212   0.186360    6.613081                         São Tomé and Príncipe
213  23.697810  120.960515                                        Taiwan
214  38.861034   71.276093                                    Tajikistan
215  -6.369028   34.888822                                      Tanzania
216  15.870032  100.992541                                      Thailand
217  -8.874217  125.727539                                   Timor-Leste
218   8.619543    0.824782                                          Togo
219  -8.967363 -171.855881                                       Tokelau
220 -21.178986 -175.198242                                         Tonga
221  10.691803  -61.222503                           Trinidad and Tobago
222  33.886917    9.537499                                       Tunisia
223  38.963745   35.243322                                        Turkey
224  38.969719   59.556278                                  Turkmenistan
225  21.694025  -71.797928                      Turks and Caicos Islands
226  -7.109535  177.649330                                        Tuvalu
227  18.335765  -64.896335                           U.S. Virgin Islands
228   1.373333   32.290275                                        Uganda
229  48.379433   31.165580                                       Ukraine
230  23.424076   53.847818                          United Arab Emirates
231  55.378051   -3.435973                                United Kingdom
232  37.090240  -95.712891                                 United States
233 -32.522779  -55.765835                                       Uruguay
234  41.377491   64.585262                                    Uzbekistan
235 -15.376706  166.959158                                       Vanuatu
236  41.902916   12.453389                                  Vatican City
237   6.423750  -66.589730                                     Venezuela
238  14.058324  108.277199                                       Vietnam
239 -13.768752 -177.156097                             Wallis and Futuna
240  24.215527  -12.885834                                Western Sahara
241  15.552727   48.516388                                         Yemen
242 -13.133897   27.849332                                        Zambia
243 -19.015438   29.154857                                      Zimbabwe

In [7]:
df_age=pd.read_csv('covid-vaccine-by-age_new.csv')
df_age.head(3)

    Entity Code      Day  80+_start  18-24_start  50-59_start  70-79_start  25-49_start  60-69_start
0  Austria  AUT   8/1/21       1.23         0.12         0.54         0.27         0.38         0.32
1  Austria  AUT  15/1/21       6.05         0.44         1.81         1.29         1.18         1.30
2  Austria  AUT  22/1/21      11.75         0.87         3.15         2.15         2.16         2.11

In [8]:
df_age.rename(columns={'Entity':'Country','Day':'Date'},inplace=True)
df_age.columns = df_age.columns.str.replace(r"_start","")

In [9]:
df_age.head(3)

   Country Code     Date    80+  18-24  50-59  70-79  25-49  60-69
0  Austria  AUT   8/1/21   1.23   0.12   0.54   0.27   0.38   0.32
1  Austria  AUT  15/1/21   6.05   0.44   1.81   1.29   1.18   1.30
2  Austria  AUT  22/1/21  11.75   0.87   3.15   2.15   2.16   2.11

In [10]:
df_owid=pd.read_csv('owid-covid-data.csv')

In [11]:
df_owid.columns

Index(['iso_code', 'continent', 'Country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'new_vaccinations_smoothed_per_million', 'population', 'population_density', 'median_age', 'gdp_per_capita', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'human_development_index'], dtype='object')

In [12]:
#renaming columns
df_owid.rename(columns={'location':'Country'},inplace=True)
df_owid.columns=df_owid.columns.str.replace(r"_smoothed","")

In [13]:
# function to convert column to datetime format
def datetime_conversion(df,column):
    df[column] =  pd.to_datetime(df[column], format='%d/%m/%y')

In [14]:
datetime_conversion(df_owid,'date')

In [15]:
df_owid.to_csv('owid-covid-data.csv')

In [18]:
ls -p . | grep /*csv

'grep' is not recognized as an internal or external command,
operable program or batch file.

In [19]:
#read data
vaccinations_doses_by_manuf=pd.read_csv('vaccination-data including type.csv')
vaccinations_doses_by_manuf.head(2)

       COUNTRY ISO3 WHO_REGION DATA_SOURCE DATE_UPDATED  TOTAL_VACCINATIONS  PERSONS_VACCINATED_1PLUS_DOSE  TOTAL_VACCINATIONS_PER100  PERSONS_VACCINATED_1PLUS_DOSE_PER100  PERSONS_FULLY_VACCINATED  PERSONS_FULLY_VACCINATED_PER100                                      VACCINES_USED FIRST_VACCINE_DATE  NUMBER_VACCINES_TYPES_USED
0  Afghanistan  AFG       EMRO   REPORTING      30/8/21             1979652                       773002.0                      5.085                                 1.986                  441371.0                            1.134  Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2...            22/2/21                         4.0
1      Albania  ALB       EURO        OWID      30/8/21             1458048                       824170.0                     50.665                                28.639                  633878.0                           22.026  AstraZeneca - AZD1222, Pfizer BioNTech - Comir...                NaN                         4.0

In [20]:
#split vaccines_used columns to individual vaccines type used
df1=vaccinations_doses_by_manuf.loc[:, vaccinations_doses_by_manuf.columns != 'VACCINES_USED']
df2=vaccinations_doses_by_manuf.VACCINES_USED.str.split(',',expand=True).add_prefix('vac_')
vaccinations_doses_by_manuf_expanded=pd.concat([df1, df2], axis=1)
vaccinations_doses_by_manuf_expanded.head(2)

       COUNTRY ISO3 WHO_REGION DATA_SOURCE DATE_UPDATED  TOTAL_VACCINATIONS  PERSONS_VACCINATED_1PLUS_DOSE  TOTAL_VACCINATIONS_PER100  PERSONS_VACCINATED_1PLUS_DOSE_PER100  PERSONS_FULLY_VACCINATED  PERSONS_FULLY_VACCINATED_PER100 FIRST_VACCINE_DATE  NUMBER_VACCINES_TYPES_USED                      vac_0                         vac_1                        vac_2                  vac_3 vac_4 vac_5 vac_6 vac_7 vac_8
0  Afghanistan  AFG       EMRO   REPORTING      30/8/21             1979652                       773002.0                      5.085                                 1.986                  441371.0                            1.134            22/2/21                         4.0  Beijing CNBG - BBIBP-CorV        Janssen - Ad26.COV 2.5  Pfizer BioNTech - Comirnaty       SII - Covishield  None  None  None  None  None
1      Albania  ALB       EURO        OWID      30/8/21             1458048                       824170.0                     50.665                                28.639                  633878.0                           22.026                NaN                         4.0      AstraZeneca - AZD1222   Pfizer BioNTech - Comirnaty          Sinovac - CoronaVac   Gamaleya - Sputnik V  None  None  None  None  None

In [21]:
vac_cols=['vac_0','vac_1', 'vac_2', 'vac_3', 'vac_4', 'vac_5', 'vac_6',
       'vac_7', 'vac_8']
#creating unique id vac_id using vaccines used
vaccinations_doses_by_manuf_expanded['vac_ID']=vaccinations_doses_by_manuf_expanded[vac_cols].apply(lambda x: ':'.join(x.dropna()), axis=1)
#removing additional "::" generated 
vaccinations_doses_by_manuf_expanded['vac_ID']= vaccinations_doses_by_manuf_expanded['vac_ID'].str.strip(r': {2,}')
vaccinations_doses_by_manuf_expanded.head(2)

       COUNTRY ISO3 WHO_REGION DATA_SOURCE DATE_UPDATED  TOTAL_VACCINATIONS  PERSONS_VACCINATED_1PLUS_DOSE  TOTAL_VACCINATIONS_PER100  PERSONS_VACCINATED_1PLUS_DOSE_PER100  PERSONS_FULLY_VACCINATED  PERSONS_FULLY_VACCINATED_PER100 FIRST_VACCINE_DATE  NUMBER_VACCINES_TYPES_USED                      vac_0                         vac_1                        vac_2                  vac_3 vac_4 vac_5 vac_6 vac_7 vac_8                                             vac_ID
0  Afghanistan  AFG       EMRO   REPORTING      30/8/21             1979652                       773002.0                      5.085                                 1.986                  441371.0                            1.134            22/2/21                         4.0  Beijing CNBG - BBIBP-CorV        Janssen - Ad26.COV 2.5  Pfizer BioNTech - Comirnaty       SII - Covishield  None  None  None  None  None  Beijing CNBG - BBIBP-CorV:Janssen - Ad26.COV 2...
1      Albania  ALB       EURO        OWID      30/8/21             1458048                       824170.0                     50.665                                28.639                  633878.0                           22.026                NaN                         4.0      AstraZeneca - AZD1222   Pfizer BioNTech - Comirnaty          Sinovac - CoronaVac   Gamaleya - Sputnik V  None  None  None  None  None  AstraZeneca - AZD1222: Pfizer BioNTech - Comir...

In [22]:
vaccinations_doses_by_manuf_expanded.to_csv('country_wise_vaccine_corrected.csv')

In [23]:
vaccine_names_correction=pd.read_csv('country_wise_vaccine_corrected.csv')

In [24]:
vaccine_names_correction.vac_0.unique()

array(['Beijing CNBG - BBIBP-CorV', 'AstraZeneca - AZD1222',
       'Janssen - Ad26.COV 2.5', 'SII - Covishield',
       'AstraZeneca - Vaxzevria', 'Beijing CNBG - Inactivated', nan,
       'Moderna - mRNA-1273', 'Pfizer BioNTech - Comirnaty',
       'Bharat - Covaxin', 'Anhui ZL - Recombinant', 'Abdala',
       'Gamaleya - Sputnik V', 'QazVac', 'SRCVB - EpiVacCorona'],
      dtype=object)

In [25]:
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Moderna - mRNA-1273', 'Moderna'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Janssen - Ad26.COV 2.5', 'Janssen'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('SRCVB - EpiVacCorona', 'EpiVacCorona'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Beijing CNBG - Inactivated', 'BBIBP-CorV'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Pfizer BioNTech - Comirnaty', 'Pfizer'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('AstraZeneca - AZD1222', 'AstraZeneca'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('AstraZeneca - Vaxzevria', 'AstraZeneca'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Anhui ZL - Recombinant', 'ZF2001'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Beijing CNBG - BBIBP-CorV', 'BBIBP-CorV'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Bharat - Covaxin', 'Covaxin'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('Gamaleya - Sputnik V', 'Sputnik V'))
vaccine_names_correction.loc[:,'vac_0':'vac_8'] = vaccine_names_correction.loc[:,'vac_0':'vac_8'].apply(lambda src: src.replace('SII - Covishield', 'AstraZeneca'))

In [26]:
vaccine_names_correction.vac_0.unique()

array(['BBIBP-CorV', 'AstraZeneca', 'Janssen', nan, 'Moderna', 'Pfizer',
       'Covaxin', 'ZF2001', 'Abdala', 'Sputnik V', 'QazVac',
       'EpiVacCorona'], dtype=object)

In [27]:
vaccine_names_correction.to_csv('country_wise_vaccine_corrected.csv')